class WarehouseTable():
    Coffee = "Coffee"
    Juice = "Juice"
    MilkAndCream = "MilkAndCream"
    Other = "Other"
    Powder = "Powder"
    Syrup = "Syrup"
    Tea = "Tea"
    Topping = "Topping"
    Unit = "Unit"
    Supplier = "Supplier"
    BankAccount = "BankAccount"
    OrderType = "OrderType"
    ReceivedOrder = "ReceivedOrder"
